# Diccionario de capítulos ICD-10-CM
# La clave es la letra inicial del código
capitulos_icd10cm = {
    'A': 'Enfermedades infecciosas y parasitarias (A00-A99)',
    'B': 'Enfermedades infecciosas y parasitarias (B00-B99)',
    'C': 'Neoplasias malignas (C00-C96)',
    'D': 'Neoplasias benignas y enf. sangre (D00-D89)',
    'E': 'Enfermedades endocrinas, nutricionales y metabólicas (E00-E89)',
    'F': 'Trastornos mentales y del comportamiento (F01-F99)',
    'G': 'Enfermedades del sistema nervioso (G00-G99)',
    'H': 'Enfermedades del ojo, oído y anexos (H00-H95)',
    'I': 'Enfermedades del sistema circulatorio (I00-I99)',
    'J': 'Enfermedades del sistema respiratorio (J00-J99)',
    'K': 'Enfermedades del sistema digestivo (K00-K95)',
    'L': 'Enfermedades de la piel y tejido subcutáneo (L00-L99)',
    'M': 'Enfermedades del sistema musculoesquelético (M00-M99)',
    'N': 'Enfermedades del sistema genitourinario (N00-N99)',
    'O': 'Embarazo, parto y puerperio (O00-O9A)',
    'P': 'Afecciones perinatales (P00-P96)',
    'Q': 'Malformaciones congénitas (Q00-Q99)',
    'R': 'Síntomas, signos y hallazgos anormales (R00-R99)',
    'S': 'Traumatismos y lesiones (S00-S99)',
    'T': 'Envenenamientos y efectos adversos (T07-T88)',
    'U': 'Códigos de uso especial / COVID-19 (U00-U85)',
    'V': 'Causas externas: transporte (V00-V99)',
    'W': 'Causas externas: caídas y accidentes (W00-W99)',
    'X': 'Causas externas: otras (X00-X99)',
    'Y': 'Causas externas: intervención médica (Y00-Y99)',
    'Z': 'Factores que influyen en el estado de salud (Z00-Z99)',
}

# Diccionario de categorías de 3 caracteres más comunes en tu dataset
# (las que ya viste con d_caract_3 — estas son las más relevantes)
categorias_relevantes = {
    'Z79': 'Uso prolongado de medicamentos',
    'Z68': 'Índice de masa corporal (IMC)',
    'E66': 'Obesidad',
    'I10': 'Hipertensión esencial',
    'F17': 'Trastornos por uso de nicotina',
    'E11': 'Diabetes mellitus tipo 2',
    'E78': 'Trastornos del metabolismo lipídico',
    'Z95': 'Presencia de implantes cardíacos y vasculares',
    'I25': 'Enfermedad isquémica crónica del corazón',
    'G47': 'Trastornos del sueño',
    'I48': 'Fibrilación y flutter auricular',
    'Z87': 'Historia personal de enfermedades',
    'Z3A': 'Semanas de gestación',
    'Z37': 'Resultado del parto',
    'J44': 'EPOC (Enfermedad Pulmonar Obstructiva Crónica)',
    'N18': 'Enfermedad renal crónica',
    'Z48': 'Encuentro de seguimiento post-procedimiento',
    'E55': 'Deficiencia de vitamina D',
    'E87': 'Otros trastornos electrolíticos',
    'UUU': 'Urgencias',
}